Fixed Jersey / Commons HttpClient interop problem
Jersey Apache Connector throws an exception while using Apache Commons
HttpClient:
java.lang.NoSuchMethodError:
org.apache.http.impl.client.HttpClientBuilder.setConnectionManagerShared
(Z)Lorg/apache/http/
impl/client/HttpClientBuilder;

The problem is that Jersey 2.18 that is used in the project calls the
method that does not exist in Apache Commons HttpClient version 3.1. A
way to fix this is to replace Jersey 2.18 with version 2.16